name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
