name: Bump tag version and deploy to dev server
on:
  push:
    branches:
      - master
jobs:
  tag-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          token: ${{ secrets.PAT }}
      - name: GitHub Tag Bump
        id: tag-bump
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Deploy to dev server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.DEV_HOST }}
          USERNAME: root
          PORT: 22
          PASSWORD: ${{ secrets.DEV_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            ~/deployment-scripts/update-serve-frontend.sh dev
